### ISSUE TITLE
Execution failure in a Python 3.9 environment due to resolved networkx being too old

### ISSUE THREAD

**Issue by ivergara** [rvalieris/conda-tree#14]
When installing `conda-tree` in a Python 3.9 environment, its execution failed. The reason is that the resolved `networkx` version was 2.3 and that version doesn't support Python 3.9. Manually upgrading to `networkx` 2.5 solved the issue.

**Comment by rvalieris** [comment]
hello, I can't reproduce this with a fresh conda install, I need more details.

1. try this command to see if it helps: `conda install -c conda-forge conda-tree 'networkx>=2.5'`
2. post your conda version and output of the conda install command with the issue

**Comment by ivergara** [comment]
Probably from a fresh install and only installing `conda-tree` it might not happen. In my case, due to other packages, `networkx` resolved to version 2.3.

I was just wondering if there was anything doable on your side to force a dependency version 2.5 for networkx when installing in Python 3.9, but I guess that falls more on that package's responsibility. 

In any case thanks! I'll close it.

**Comment by rvalieris** [comment]
yes I understand, I could try to add 'networkx>=2.5' to conda-tree but then conda might just decide to install a older version of conda-tree without the restriction, just like its happening here with networkx...

I think `conda install -c conda-forge conda-tree 'networkx>=2.5'` should help tho, I will add this to the readme.

**Comment by ivergara** [comment]
Adding it to the readme might be a good solution. The problem of adding `networkx>=2.5` is that that's only needed for Python 3.9 and not to older versions.
