### ISSUE TITLE
Can't find the seaborn or matplotlib packages

### ISSUE THREAD

**Issue by joelostblom** [rvalieris/conda-tree#18]
`conda-tree depends -t seaborn` returns `warning: package "seaborn" not found` although `conda search seaborn` returns multiple matches. The same thing happnes with `matplotlib` but not with `altair`, `numpy`, `pandas`, or `scipy`. This is with `conda-tree 1.0.5`

![image](https://user-images.githubusercontent.com/4560057/163722689-1347514f-8402-47af-bd87-e778b3746c9a.png)

**Comment by rvalieris** [comment]
hello,

conda-tree can only show information about packages currently installed, the warning message is saying that there is no "seaborn" in the list of packages installed.

**Comment by joelostblom** [comment]
Oh I see, I thought it worked similar to what `conda search --reverse-dependency` used to do and didn't realize it was only for installed packages. Thanks!
