### ISSUE TITLE
WARNING: The conda.install module is deprecated and will be removed in a future release.

### ISSUE THREAD

**Issue by pb-cdunn** [rvalieris/conda-tree#2]
Great little utility. I'm using it to solve
https://github.com/conda-forge/conda-forge.github.io/issues/701

However, I see this warning:
```
WARNING: The conda.install module is deprecated and will be removed in a future release.
```

**Comment by rvalieris** [comment]
thanks for the heads up, I hadn't noticed this warning yet.

**Comment by rvalieris** [comment]
should be solved now !

**Comment by mubasharkhan** [comment]
So what will be the alternative?

**Comment by rvalieris** [comment]
> So what will be the alternative?

in this case, `conda.exports` provides the same methods I was using before.
