### ISSUE TITLE
Conda tree should default to current environment

### ISSUE THREAD

**Issue by davidfokkema** [rvalieris/conda-tree#8]
The conda tree commands default to the root environment, even if another environment is currently activated. This feels a bit misleading:
```
$ conda activate myenv

<myenv> $ conda tree leaves
# shows root environment instead

<myenv> $ conda tree -n myenv leaves
# feels unnecessary, I already have the myenv environment activated
```
(Wonderful tool BTW!)

**Comment by rvalieris** [comment]
I agree ! I meant to do that for a while, but I always forget.
a new version should be built and released in the next days.

**Comment by davidfokkema** [comment]
Great, thanks!
